### ISSUE TITLE
Error when changing visibility on Private works

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2657] opened 2024-08-21 18:03 UTC
### Descriptive summary
Attempts to change visibility to Private or from Private to something else results in this window (after clicking yes to Apply changes to contents)

ir.library.oregonstate.edu/concern/permissions/np193d91t/copy_access
<img width="323" alt="Screenshot 2024-08-21 at 10 35 33 AM" src="https://github.com/user-attachments/assets/5be3d0ef-c10e-4607-99db-f987fb5c0afb">

If you access the record again, it has the correct visibility. It's like the system gets stuck on the unauthorized part even for admin. 

### Expected behavior
Can change a Private item to Public or OSU-only or vice versa without being considered Unauthorized!

### Actual behavior
Get Unauthorized if changing something to Private or from Private to something else.

### Steps to reproduce the behavior
Note: I could not replicate this on staging.

1. Click edit on an item (example: `8623hz31p`)
2. Select Private visibility + submit.
3. Apply changes to contents? Yes please.
4. Get unauthorized message.
5. Access record again and see the changes went through. 
6. Please set item back to Public!

**Comment by lamtu1** [comment] 2024-08-21 20:59
Hi @simholt, I was wondering if this ticket related to ticket #2590 ?

**Comment by simholt** [comment] 2024-08-21 21:07
I don’t think so? That was a different sort of error.

**Comment by lamtu1** [comment] 2024-08-22 16:44
So after testing on both `staging & local env` the whole process is fine with me as it allows the work to switch to private and load just fine and was able to access it. I couldn't reproduce this error as well

**Comment by straleyb** [comment] 2024-09-26 15:03
I also attempted to reproduce this error on https://ir-staging.library.oregonstate.edu/concern/open_educational_resources/fn106z116?locale=en

I switched it from public to private to OSU-Only back to private then to public again and it never hit the routing unautorized error. This can go through QA to check but might have been resolved via other updates.

**Comment by carakey** [comment] 2024-09-27 15:59
I also couldn't reproduce the error when testing on one of my own works in Prod. Went public to private and back to public without any trouble. Closing the ticket, but we can reopen if it pops up again.

**Closed by carakey** 2024-09-27 15:59 UTC
Labels: Bug, Priority: Low
