### ISSUE TITLE
"Transfer Ownership" of a work doesn't seem to work

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1067] opened 2017-12-01 16:41 UTC
@simholt created a work, transferred ownership to the proper owner..  user logged in and was told that they were not authorized

**Comment by luisgreg99** [comment] 2017-12-09 01:41
We did some testing to double check the expected behavior when transferring ownership of a work with @wickr and found that the user is required to have access to the admin set in which the work was ingested, ie. we can have the user or group `Registered Users` listed under `Edit Administrative Set -> Participants -> Depositors`

Regardless of the ownership, when the work is already ingested, it looks like the work is only visible during the `Changes Required` workflow state. This is the default behavior defined in the workflow configuration. For example for GTDs, the edit is revoked when the work is under `Graduate School Review`, `Library Review`,  and `Restart Review Process` states. We can change this behavior if needed.

**Comment by simholt** [comment] 2018-12-04 18:46
This seems to be working now.

**Closed by simholt** 2018-12-04 18:46 UTC
Labels: Bug, Need Review, Priority: High
