### ISSUE TITLE
Unkown agent type ''

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1441] opened 2018-06-06 17:05 UTC
After a failed save and all the fields are fixed, it throws an error `unknown agent type ''`

**Comment by vantuyls** [comment] 2018-06-11 15:50
to reproduce:
1) go to ingest an item
2) fill out a field that will invalidate the save
3) save and it will create this error

**Comment by luisgreg99** [comment] 2019-04-26 18:04
The error seems to be coming from hydra-head: https://github.com/samvera/hydra-head/blob/master/hydra-access-controls/app/models/hydra/access_controls/permission.rb#L78

`Hydra::AdminPolicy` only accepts two agent types when it builds default permissions: `group` or `user`. If the type is blank, it raises the unknown agent type error.

I tried in the console and the error raises when I assigned type to an empty string `""`:

```
public_policy = Hydra::AdminPolicy.create(title: ['Public Access'])

=> #<Hydra::AdminPolicy id: "72262347-240a-456e-891c-d413d006fbb5", title: "Public Access", description: nil, default_permission_ids: [], default_embargo_id: nil, access_control_id: "f85b2b2c-b170-4354-9005-ab22c0939a99">

public_policy.default_permissions.build(type: "", name: "public", access: "read")

Traceback (most recent call last):
       15: from bin/rails:4:in `<main>'
       14: from bin/rails:4:in `require'
       13: from /usr/local/bundle/gems/railties-5.0.7/lib/rails/commands.rb:18:in `<top (required)>'
       12: from /usr/local/bundle/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
       11: from /usr/local/bundle/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:78:in `console'
       10: from /usr/local/bundle/gems/railties-5.0.7/lib/rails/commands/console_helper.rb:9:in `start'
        9: from /usr/local/bundle/gems/railties-5.0.7/lib/rails/commands/console.rb:65:in `start'
        8: from (irb):5
        7: from /usr/local/bundle/gems/active-fedora-11.5.2/lib/active_fedora/associations/collection_proxy.rb:232:in `build'
        6: from /usr/local/bundle/gems/active-fedora-11.5.2/lib/active_fedora/associations/collection_association.rb:143:in `build'
        5: from /usr/local/bundle/gems/active-fedora-11.5.2/lib/active_fedora/associations/association.rb:208:in `build_record'
        4: from /usr/local/bundle/gems/active-fedora-11.5.2/lib/active_fedora/reflection.rb:164:in `build_association'
        3: from /usr/local/bundle/gems/active-fedora-11.5.2/lib/active_fedora/reflection.rb:164:in `new'
        2: from /usr/local/bundle/gems/hydra-access-controls-10.5.1/app/models/hydra/access_controls/permission.rb:14:in `initialize'
        1: from /usr/local/bundle/gems/hydra-access-controls-10.5.1/app/models/hydra/access_controls/permission.rb:78:in `build_agent'
ArgumentError (Unknown agent type "")
```

I suspect that during validation, possibly during a form reload (or when validation fails in certain cases) the agent `type` gets the empty string.

**Comment by revgum** [comment] 2019-04-29 21:08
I'm not having luck recreating this on staging, does anyone know a repeatable way of causing this error? @vantuyls @straleyb

**Comment by vantuyls** [comment] 2019-04-30 14:43
i'm not seeing a field that is behaving this way any more. this might be closeable. @straleyb do you know of any metadata fields into which one could place an invalid input that might replicate this issue?

**Comment by luisgreg99** [comment] 2019-05-07 15:44
I think we can close this one. I did a grep on recent logs, and didn't find the error there. It might have been already fixed. We can revisit or reopen it if we see it again.

**Closed** 2019-05-07 20:47 UTC
Labels: Bug, Priority: High
