### ISSUE TITLE
TriplePoweredProperties URIs are being faceted rather than label values

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#451] opened 2016-08-12 23:18 UTC
Make the label values the facets

**Comment by wickr** [comment] 2016-08-12 23:22
Agree, though if it's just the Label value for the facet, anything that shares the same label will get faceted together, which at least for some fields is not what we want.

**Comment by vantuyls** [comment] 2016-08-12 23:23
@wickr do you have an example of that happening?

**Comment by wickr** [comment] 2016-08-12 23:59
Looking more at this, I found the Oregon Digital 2 ticket where we were discussing this: 
https://github.com/OregonDigital/oregondigital_2/issues/21

In OD1, facets are unique based on URI. The saved, faceted field is "Label$URI" but URI is stripped before displaying it. This can make the same concept with different URIs from different vocabularies show up as separate facets (my Periodicals example from the OD2 ticket). 

This didn't seem to be desired in OD2, though I'm not convinced it works for certain fields where the concepts are clearly different (hypothetical but "Orange" the color vs. "Orange" the fruit, if that's all the labels are then they'd be together).  

Names are an area I don't think we'll want to collapse similar labels if they're known to be different people, but others disagree.  (and if we don't have Creators in SA as linked data at the beginning it's going to happen anyway if there's ever the same name).

Part of the problem is sometimes you can't tell if something is actually different, and we normally don't have a way to edit the labels we get back from fetches.

Maybe we only deal with this if it becomes an issue later.

**Comment by wickr** [comment] 2016-08-13 01:42
I'll make another ticket for Geonames place labels, because I think those should get this attention, but they don't by default include more information to disambiguate. So Salem, OR and Salem, MA both have their label as "Salem" and that's it.

**Comment by vantuyls** [comment] 2017-04-24 19:47
closing as no longer relevant

**Closed by vantuyls** 2017-04-24 19:47 UTC
Labels: critical
