### ISSUE TITLE
Reindexing times out

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#867] opened 2017-08-24 19:52 UTC
`bundle exec rails solr:reindex` eventually fails because of a timeout. 

```
2017-08-24T19:49:35.275Z 32153 TID-ot99cdbxk WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ResolrizeJob","queue":"default","args":[{"job_class":"ResolrizeJob","job_id":"b19d3322-fc7e-48f2-ae6e-1b79f2050704","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[],"locale":"en"}],"retry":true,"jid":"55b185e5a9f1d9093454ac2a","created_at":1503603638.7602463,"enqueued_at":1503604055.134504,"error_message":"Net::ReadTimeout","error_class":"Faraday::TimeoutError","failed_at":1503603758.864553,"retry_count":2,"retried_at":1503604175.2744203},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ResolrizeJob\",\"queue\":\"default\",\"args\":[{\"job_class\":\"ResolrizeJob\",\"job_id\":\"b19d3322-fc7e-48f2-ae6e-1b79f2050704\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[],\"locale\":\"en\"}],\"retry\":true,\"jid\":\"55b185e5a9f1d9093454ac2a\",\"created_at\":1503603638.7602463,\"enqueued_at\":1503604055.134504,\"error_message\":\"Net::ReadTimeout\",\"error_class\":\"Faraday::TimeoutError\",\"failed_at\":1503603758.864553,\"retry_count\":1,\"retried_at\":1503604018.958254}"}
2017-08-24T19:49:35.275Z 32153 TID-ot99cdbxk WARN: Faraday::TimeoutError: Net::ReadTimeout
...
```

**Comment by vantuyls** [comment] 2017-09-07 18:21
@revgum suggests hitting up samvera #dev to ask how folks have dealt with this.

**Comment by vantuyls** [comment] 2017-09-07 18:26
also check Samvera Tech google group for possible info.

**Comment by luisgreg99** [comment] 2017-10-16 16:16
From sidekiq logs, we found that we get the `Net::ReadTimeout` in ActiveFedora when it tries to query the main graph to build the array for the immediate descendant uris: https://github.com/samvera/active_fedora/blob/v11.3.1/lib/active_fedora/indexing/descendant_fetcher.rb#L52

We can reproduce the `Net::ReadTimeout` error in the console with:
```
u = ActiveFedora.fedora.base_uri
begin
  response = ActiveFedora.fedora.connection.get(u)
rescue => e
  puts e
end
```

If we inspect the backtrace, we can see the full stack of the request:

```
e.backtrace.each { |e| puts e.inspect }
```
```
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:1437:in `block in transport_request'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:1407:in `request'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:1400:in `block in request'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:853:in `start'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:1398:in `request'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:1156:in `get'
**/data0/hydra/shared/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:78:in `perform_request'**
/data0/hydra/shared/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:38:in `block in call'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:33:in `call'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/faraday-encoding-0.0.4/lib/faraday/encoding.rb:12:in `call'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/connection.rb:149:in `get'
**/data0/hydra/shared/bundle/ruby/2.3.0/gems/ldp-0.7.0/lib/ldp/client/methods.rb:35:in `block in get'**
/data0/hydra/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/notifications.rb:166:in `instrument'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/ldp-0.7.0/lib/ldp/client/methods.rb:33:in `get'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/active-fedora-11.5.0/lib/active_fedora/caching_connection.rb:13:in `get'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/active-fedora-11.5.0/lib/active_fedora/initializing_connection.rb:27:in `get'
"(irb):3:in `irb_binding'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/irb/workspace.rb:87:in `eval'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/irb/workspace.rb:87:in `evaluate'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/irb/context.rb:380:in `evaluate'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/irb.rb:489:in `block (2 levels) in eval_input'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/irb.rb:623:in `signal_status'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/irb.rb:486:in `block in eval_input'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `loop'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `catch'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/irb.rb:485:in `eval_input'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/irb.rb:395:in `block in start'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/irb.rb:394:in `catch'
/usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/irb.rb:394:in `start'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/commands/console.rb:65:in `start'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/commands/console_helper.rb:9:in `start'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:78:in `console'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
"bin/rails:4:in `require'
"bin/rails:4:in `<main>'
```

**Comment by luisgreg99** [comment] 2017-10-19 17:30
Posted a topic in samvera-tech:
https://groups.google.com/d/msg/samvera-tech/FPSFJubcPn8/cOr7_mJ_BAAJ

From the discussion, it looks like there's open jira ticket related to this issue:
https://jira.duraspace.org/browse/FCREPO-2544

**Comment by vantuyls** [comment] 2017-11-14 19:02
@luisgreg99 can we close this issue?

**Comment by luisgreg99** [comment] 2017-11-14 19:12
@vantuyls yes, we can close it. For this task we are now using this job https://github.com/osulp/Scholars-Archive/blob/master/app/jobs/reindex_everything_job.rb to do the reindex. 

Also, it looks like there has been some updates/progress on the existing jira ticket about the main issue https://jira.duraspace.org/browse/FCREPO-2544. Once this ticket is resolved, we would be able to also use the built-in job in active-fedora: https://github.com/osulp/Scholars-Archive/blob/master/app/jobs/resolrize_job.rb

**Closed by luisgreg99** 2017-11-14 19:12 UTC
Labels: bug, critical, MS2
